name: Morning Report

on:
  schedule:
    - cron: '0 22 * * *'  # 每天 22 点 UTC 时间（北京时间早上 6 点）
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run LifeSync-AI Script
      env:
        ENV_NOTION_TOKEN: ${{ secrets.ENV_NOTION_TOKEN }}
        ENV_DATABASE_ID: ${{ secrets.ENV_DATABASE_ID }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        AI_API_KEY: ${{ secrets.AI_API_KEY }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        WEATHER_CITY_NAME: ${{ secrets.WEATHER_CITY_NAME }}
      run: |
        python main.py
